Repository BEarSTudent/Capstone, pull requests merged in 2024-06, with the labels that each got.

#52 ST_02
  gen/README.md
  gen/app.py
  web/app/__init__.py
  web/app/static/css/transfer_style.css
  web/app/static/js/transfer.js
  web/app/templates/transfer/transfer.html
Labels: enhancement

#54 Readme
  README.md
  ai/README.md
  gen/README.md
Labels: documentation

#56 Bugfix
  web/app/__init__.py
  web/app/templates/transfer/wait.html
Labels: bug

#58 Bugfix
  INSTALL&DRIVE.md
  README.md
  ai/README.md
  ai/app.py
  gen/README.md
  web/app/__init__.py
  web/app/static/css/new_board_popup_style.css
  web/app/static/images/main/stex_3_2.png
  web/app/static/images/main/stex_4_2.jpg
  web/app/static/images/transfer/generative_model_ex.png
  web/app/static/js/register.js
  web/app/static/js/transfer.js
  web/app/templates/auth/register.html
  web/app/templates/index.html
  web/app/templates/member/new_board_popup.html
  web/app/templates/transfer/transfer.html
Labels: bug

#59 Develop
  INSTALL&DRIVE.md
  README.md
  ai/README.md
  ai/app.py
  gen/README.md
  web/app/__init__.py
  web/app/static/css/new_board_popup_style.css
  web/app/static/images/main/stex_3_2.png
  web/app/static/images/main/stex_4_2.jpg
  web/app/static/images/transfer/generative_model_ex.png
  web/app/static/js/register.js
  web/app/static/js/transfer.js
  web/app/templates/auth/register.html
  web/app/templates/index.html
  web/app/templates/member/new_board_popup.html
  web/app/templates/transfer/transfer.html
Labels: bug, enhancement
